# Generated by Django 5.2.1 on 2025-05-27 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nachname')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Foto')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gültig von')),
                ('valid_to', models.DateTimeField(verbose_name='Gültig bis')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR-Code')),
            ],
        ),
    ]
