# Generated by Django 5.2.1 on 2025-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(upload_to='qrcodes/', verbose_name='QR-Code'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Ticket-Nr'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Gültig von'),
        ),
    ]
