# Generated by Django 5.2.1 on 2025-05-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_photo_alter_ticket_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='territory',
            field=models.CharField(default='Deutschlandweit', max_length=100, verbose_name='Geltungsbereich'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_class',
            field=models.CharField(default='2. Klasse', max_length=50, verbose_name='Klasse'),
        ),
    ]
